<a href="https://colab.research.google.com/github/mrasilbek19/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

2.2.3

In [ ]:

import pandas as pd

mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "KIA"],
    'counts': [3, 7, 2, 8, 1, 9, 4]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      KIA       4

In [ ]:
df.head(2) # default 5 rows

    cars  counts
0    BMW       3
1  Volvo       7

In [ ]:
df.tail() # default 5 rows

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      KIA       4

In [ ]:
df.shape

(7, 2)

In [ ]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [ ]:
df.dtypes

cars      object
counts     int64
dtype: object

In [ ]:
df.describe()

         counts
count  7.000000
mean   4.857143
std    3.132016
min    1.000000
25%    2.500000
50%    4.000000
75%    7.500000
max    9.000000

In [ ]:
df.iloc[2]

cars      Ford
counts       2
Name: 2, dtype: object

In [ ]:
df.loc[2:5, "cars"]

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [ ]:
df[df["cars"] == "KIA" ]

  cars  counts
6  KIA       4

In [ ]:
df.mean(numeric_only=True)

counts    4.857143
dtype: float64

In [ ]:
df["counts"].mean()

np.float64(4.857142857142857)

In [ ]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordKIA
counts                                 34
dtype: object

In [ ]:
df.min()

cars      BMW
counts      1
dtype: object

In [ ]:
df.max()

cars      Volvo
counts        9
dtype: object

In [ ]:
df.median(numeric_only=True)

counts    4.0
dtype: float64

In [ ]:
df.count()

cars      7
counts    7
dtype: int64

In [ ]:
df.std(numeric_only=True)

counts    3.132016
dtype: float64

In [ ]:
import pandas as pd

data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [ ]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [ ]:
df_missing.dropna(subset=["cars"])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
6     Ford     NaN

In [ ]:
df_missing.fillna({"cars":"unknown", "counts":0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [ ]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.to_excel("test.xlsx")

In [ ]:
# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [ ]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']